groups:
  - name: kafka_services
    rules:
      # Producer Service Alerts
      - alert: ProducerServiceDown
        expr: up{job="producer-service"} == 0
        for: 1m
        labels:
          severity: critical
          service: producer
        annotations:
          summary: "Producer Service недоступен"
          description: "Producer Service не отвечает более 1 минуты"

      - alert: ProducerHighErrorRate
        expr: rate(producer_events_failed_total[5m]) / rate(producer_events_published_total[5m]) > 0.05
        for: 2m
        labels:
          severity: critical
          service: producer
        annotations:
          summary: "Высокий процент ошибок в Producer Service"
          description: "Процент ошибок превышает 5% за последние 5 минут"

      - alert: ProducerHighLatency
        expr: histogram_quantile(0.95, rate(producer_publish_duration_seconds_bucket[5m])) > 0.5
        for: 2m
        labels:
          severity: warning
          service: producer
        annotations:
          summary: "Высокая латентность Producer Service"
          description: "95-й перцентиль времени публикации превышает 500ms"

      # Consumer Service Alerts
      - alert: ConsumerServiceDown
        expr: up{job="consumer-service"} == 0
        for: 1m
        labels:
          severity: critical
          service: consumer
        annotations:
          summary: "Consumer Service недоступен"
          description: "Consumer Service не отвечает более 1 минуты"

      - alert: ConsumerLagHigh
        expr: kafka_consumergroup_lag > 1000
        for: 5m
        labels:
          severity: warning
          service: consumer
        annotations:
          summary: "Большой лаг в Consumer Service"
          description: "Лаг консьюмера превышает 1000 сообщений"

      - alert: ConsumerHighErrorRate
        expr: rate(consumer_events_failed_total[5m]) / rate(consumer_events_consumed_total[5m]) > 0.05
        for: 2m
        labels:
          severity: critical
          service: consumer
        annotations:
          summary: "Высокий процент ошибок в Consumer Service"
          description: "Процент ошибок превышает 5% за последние 5 минут"

      # Kafka Alerts
      - alert: KafkaBrokerDown
        expr: kafka_brokers < 1
        for: 1m
        labels:
          severity: critical
          service: kafka
        annotations:
          summary: "Kafka брокер недоступен"
          description: "Kafka брокер не отвечает"

      - alert: KafkaTopicLagHigh
        expr: sum by(topic) (kafka_topic_partition_current_offset) - sum by(topic) (kafka_topic_partition_oldest_offset) > 10000
        for: 5m
        labels:
          severity: warning
          service: kafka
        annotations:
          summary: "Большой лаг в Kafka топике"
          description: "Разница между текущим и старейшим офсетом превышает 10000"

      # System Alerts
      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total[5m]) > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Высокая загрузка CPU"
          description: "Использование CPU превышает 80% за последние 5 минут"

      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes / process_virtual_memory_bytes > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Высокое использование памяти"
          description: "Использование памяти превышает 80% за последние 5 минут" 