groups:
  - name: latency.rules
    rules:
      - alert: HighLatency
        expr: histogram_quantile(0.99, rate(http_request_duration_seconds_bucket[1m])) > 0.25
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Высокая задержка p99 в течение последней минуты"
