global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'telegram-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'telegram-critical'
      group_wait: 10s
      repeat_interval: 1h
    - match:
        severity: warning
      receiver: 'telegram-notifications'

receivers:
  - name: 'telegram-critical'
    telegram_configs:
      - bot_token: 7514271624:AAH7Uwr76mKLaK0QMzqBqe07mQNlmmCL4fo
        chat_id: 825412089
        api_url: 'https://api.telegram.org'
        parse_mode: 'HTML'
        send_resolved: true
        message: |
          🚨 <b>КРИТИЧЕСКАЯ ОШИБКА!</b>
          
          <b>Алерт:</b> {{ .GroupLabels.alertname }}
          <b>Сервис:</b> {{ .GroupLabels.service }}
          <b>Важность:</b> {{ .CommonLabels.severity }}
          
          <b>Описание:</b> {{ .CommonAnnotations.description }}
          
          <b>Затронуто:</b> {{ .CommonLabels.instance }}
          <b>Время:</b> {{ .StartsAt.Format "02.01.2006 15:04:05" }}

  - name: 'telegram-notifications'
    telegram_configs:
      - bot_token: 7514271624:AAH7Uwr76mKLaK0QMzqBqe07mQNlmmCL4fo
        chat_id: 825412089
        api_url: 'https://api.telegram.org'
        parse_mode: 'HTML'
        send_resolved: true
        message: |
          ⚠️ <b>Предупреждение</b>
          
          <b>Алерт:</b> {{ .GroupLabels.alertname }}
          <b>Сервис:</b> {{ .GroupLabels.service }}
          <b>Важность:</b> {{ .CommonLabels.severity }}
          
          <b>Описание:</b> {{ .CommonAnnotations.description }}
          
          <b>Затронуто:</b> {{ .CommonLabels.instance }}
          <b>Время:</b> {{ .StartsAt.Format "02.01.2006 15:04:05" }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service'] 