groups:
  - name: kafka_services
    rules:
      # Producer Service Alerts
      - alert: ProducerServiceDown
        expr: up{job="producer-service"} == 0
        for: 30s
        labels:
          severity: critical
          service: producer
        annotations:
          summary: "Producer Service недоступен"
          description: "Producer Service не отвечает более 30 секунд"

      - alert: ProducerHighErrorRate
        expr: rate(producer_events_failed_total[1m]) / rate(producer_events_published_total[1m]) > 0.002
        for: 30s
        labels:
          severity: critical
          service: producer
        annotations:
          summary: "Высокий процент ошибок в Producer Service"
          description: "Процент ошибок превышает 0.2% за последнюю минуту"

      - alert: ProducerHighLatency
        expr: histogram_quantile(0.95, rate(producer_publish_duration_seconds_bucket[1m])) > 0.15
        for: 1m
        labels:
          severity: warning
          service: producer
        annotations:
          summary: "Высокая латентность Producer Service"
          description: "95-й перцентиль времени публикации превышает 150ms"

      # Consumer Service Alerts
      - alert: ConsumerServiceDown
        expr: up{job="consumer-service"} == 0
        for: 30s
        labels:
          severity: critical
          service: consumer
        annotations:
          summary: "Consumer Service недоступен"
          description: "Consumer Service не отвечает более 30 секунд"

      - alert: ConsumerLagHigh
        expr: kafka_consumergroup_lag > 5000
        for: 2m
        labels:
          severity: warning
          service: consumer
        annotations:
          summary: "Большой лаг в Consumer Service"
          description: "Лаг консьюмера превышает 5000 сообщений"

      - alert: ConsumerHighErrorRate
        expr: rate(consumer_events_failed_total[1m]) / rate(consumer_events_consumed_total[1m]) > 0.002
        for: 30s
        labels:
          severity: critical
          service: consumer
        annotations:
          summary: "Высокий процент ошибок в Consumer Service"
          description: "Процент ошибок превышает 0.2% за последнюю минуту"

      # Kafka Alerts
      - alert: KafkaBrokerDown
        expr: kafka_brokers < 1
        for: 1m
        labels:
          severity: critical
          service: kafka
        annotations:
          summary: "Kafka брокер недоступен"
          description: "Kafka брокер не отвечает"