receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  
  # Prometheus receiver для self-monitoring
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 30s
          static_configs:
            - targets: ['localhost:8888']

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048
  
  memory_limiter:
    limit_mib: 400
    spike_limit_mib: 100
    check_interval: 1s
  
  resource:
    attributes:
      - key: environment
        value: development
        action: insert
      - key: service.namespace
        value: diploma-project
        action: insert
  
  # Resource detection
  resourcedetection:
    detectors: [env, system, docker]
    timeout: 5s
    override: false

exporters:
  # OTLP exporter для Jaeger
  otlp/jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  
  # Prometheus exporter для метрик
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: otelcol
    const_labels:
      environment: development
  
  # Loki exporter для логов
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    default_labels_enabled:
      exporter: false
      job: true
  
  # Logging exporter для отладки
  logging:
    loglevel: info
    sampling_initial: 5
    sampling_thereafter: 200

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  
  pprof:
    endpoint: 0.0.0.0:1777
  
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, pprof, zpages]
  
  pipelines:
    # Traces pipeline
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, resource, batch]
      exporters: [otlp/jaeger, logging]
    
    # Metrics pipeline
    metrics:
      receivers: [otlp, prometheus]
      processors: [memory_limiter, resourcedetection, resource, batch]
      exporters: [prometheus, logging]
    
    # Logs pipeline
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, resource, batch]
      exporters: [loki, logging]
  
  telemetry:
    metrics:
      address: 0.0.0.0:8888 