global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'diploma-project'
    environment: 'development'

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Producer Service - публикует события в Kafka
  - job_name: 'producer-service'
    static_configs:
      - targets: ['producer-service:9090']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '(producer_.*|http_.*)'
        target_label: service
        replacement: 'producer'

  # Consumer Service
  - job_name: 'consumer-service'
    static_configs:
      - targets: ['consumer-service:9090']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '(consumer_.*|http_.*)'
        target_label: service
        replacement: 'consumer'

  # Kafka метрики
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Prometheus сам себя
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s